import type { StructureProfile } from "@adce/shared";

export const PROFILES: Record<string, StructureProfile> = {
  /**
   * Language-agnostic ADCE knowledge baseline.
   * Required = minimal; recommended = "would be nice" engineering artifacts
   * from the original ADCE vision (requirements → design → architecture → …).
   */
  "software-eng": {
    id: "software-eng",
    name: "Software engineering baseline",
    description:
      "Universal ADCE knowledge layout: requirements, design, architecture, decisions, security, schemas, API, testing",
    rules: [
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
      {
        id: "requirements",
        level: "recommended",
        type: "REQUIREMENT",
        pathGlob: "requirements/**/*.{md,mdx}",
        minCount: 1,
        description: "Requirements under requirements/",
      },
      {
        id: "design",
        level: "recommended",
        type: "DESIGN",
        pathGlob: "design/**/*.{md,mdx}",
        minCount: 1,
        description: "Design notes under design/",
      },
      {
        id: "architecture",
        level: "recommended",
        type: "ARCHITECTURE",
        pathGlob: "architecture/**/*.{md,mdx}",
        minCount: 1,
        description: "Architecture docs under architecture/",
      },
      {
        id: "decisions",
        level: "recommended",
        type: "DECISION",
        pathGlob: "{decisions,docs/adr,adr}/**/*.{md,mdx}",
        minCount: 1,
        description: "Architecture Decision Records (ADR)",
      },
      {
        id: "security",
        level: "recommended",
        type: "POLICY",
        pathGlob: "{security,policy,policies}/**/*.{md,mdx}",
        minCount: 1,
        description: "Security / policy specs",
      },
      {
        id: "schemas",
        level: "recommended",
        type: "SCHEMA",
        pathGlob: "schemas/**/*.{json,sql,prisma}",
        minCount: 1,
        description: "Database / data schemas under schemas/",
      },
      {
        id: "api-spec",
        level: "recommended",
        type: "API_SPEC",
        pathGlob:
          "{openapi.yaml,openapi.yml,openapi.json,swagger.yaml,swagger.yml}",
        minCount: 1,
        description: "API contract (OpenAPI / Swagger at repo root)",
      },
      {
        id: "testing-strategy",
        level: "recommended",
        type: "SPECIFICATION",
        pathGlob: "{docs/testing,testing}/**/*.{md,mdx}",
        minCount: 1,
        description: "Testing strategy under docs/testing/ or testing/",
      },
      {
        id: "source",
        level: "recommended",
        type: "SOURCE",
        minCount: 1,
        description: "At least one source artifact",
      },
      {
        id: "tests",
        level: "recommended",
        type: "TEST",
        minCount: 1,
        description: "At least one automated test artifact",
      },
    ],
    relationshipRules: [
      {
        id: "docs-link",
        level: "recommended",
        relationshipType: "DOCUMENTS",
        check: "any-documents-edge",
        description: "Docs / specs linked to implementation",
      },
    ],
  },
  "typescript-lib": {
    id: "typescript-lib",
    name: "TypeScript library",
    description: "README, package.json, src, tests",
    rules: [
      {
        id: "manifest",
        level: "required",
        type: "DEPENDENCY_MANIFEST",
        pathGlob: "package.json",
        description: "package.json present",
      },
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "src/**/*.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one source file under src/",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "**/*.{test,spec}.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one test file",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
      {
        id: "tsconfig",
        level: "recommended",
        type: "BUILD",
        pathGlob: "tsconfig.json",
        description: "TypeScript config",
      },
    ],
    relationshipRules: [
      {
        id: "tests-link",
        level: "recommended",
        relationshipType: "TESTS",
        check: "test-naming-sibling",
        description: "Tests linked to sibling sources",
      },
    ],
  },
  "typescript-api": {
    id: "typescript-api",
    name: "TypeScript API service",
    description: "Library layout plus OpenAPI/Swagger spec",
    rules: [
      {
        id: "manifest",
        level: "required",
        type: "DEPENDENCY_MANIFEST",
        pathGlob: "package.json",
        description: "package.json present",
      },
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "src/**/*.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one source file under src/",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "**/*.{test,spec}.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one test file",
      },
      {
        id: "openapi",
        level: "required",
        type: "API_SPEC",
        pathGlob: "{openapi.yaml,openapi.yml,openapi.json,swagger.yaml,swagger.yml}",
        description: "OpenAPI or Swagger spec at repo root",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
      {
        id: "tsconfig",
        level: "recommended",
        type: "BUILD",
        pathGlob: "tsconfig.json",
        description: "TypeScript config",
      },
    ],
    relationshipRules: [
      {
        id: "tests-link",
        level: "recommended",
        relationshipType: "TESTS",
        check: "test-naming-sibling",
        description: "Tests linked to sibling sources",
      },
      {
        id: "docs-link",
        level: "recommended",
        relationshipType: "DOCUMENTS",
        check: "any-documents-edge",
        description: "Spec or docs linked to implementation",
      },
    ],
  },
  generic: {
    id: "generic",
    name: "Generic project",
    description: "README, source, and tests — language-light",
    rules: [
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "**/*.{ts,tsx,js,jsx,py,go,rs,java}",
        minCount: 1,
        description: "At least one source file",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "**/*.{test,spec}.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one JS/TS-style test file",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
    ],
  },
  go: {
    id: "go",
    name: "Go module",
    description: "go.mod, packages, *_test.go",
    rules: [
      {
        id: "manifest",
        level: "required",
        type: "DEPENDENCY_MANIFEST",
        pathGlob: "go.mod",
        description: "go.mod present",
      },
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "**/*.go",
        minCount: 1,
        description: "At least one Go source file",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "**/*_test.go",
        minCount: 1,
        description: "At least one *_test.go file",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
    ],
  },
  python: {
    id: "python",
    name: "Python project",
    description: "pyproject/requirements, package code, pytest-style tests",
    rules: [
      {
        id: "manifest",
        level: "required",
        type: "DEPENDENCY_MANIFEST",
        pathGlob: "{pyproject.toml,requirements.txt}",
        description: "pyproject.toml or requirements.txt",
      },
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "**/*.py",
        minCount: 1,
        description: "At least one Python source file",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "{**/test_*.py,**/*_test.py,tests/**/*.py}",
        minCount: 1,
        description: "At least one pytest-style test",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
    ],
  },
};

export const DEFAULT_PROFILE_ID = "software-eng";
