import type { StructureProfile } from "@adce/shared";

export const PROFILES: Record<string, StructureProfile> = {
  "typescript-lib": {
    id: "typescript-lib",
    name: "TypeScript library",
    description: "README, package.json, src, tests",
    rules: [
      {
        id: "manifest",
        level: "required",
        type: "DEPENDENCY_MANIFEST",
        pathGlob: "package.json",
        description: "package.json present",
      },
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "src/**/*.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one source file under src/",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "**/*.{test,spec}.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one test file",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
      {
        id: "tsconfig",
        level: "recommended",
        type: "BUILD",
        pathGlob: "tsconfig.json",
        description: "TypeScript config",
      },
    ],
    relationshipRules: [
      {
        id: "tests-link",
        level: "recommended",
        relationshipType: "TESTS",
        check: "test-naming-sibling",
        description: "Tests linked to sibling sources",
      },
    ],
  },
  "typescript-api": {
    id: "typescript-api",
    name: "TypeScript API service",
    description: "Library layout plus OpenAPI/Swagger spec",
    rules: [
      {
        id: "manifest",
        level: "required",
        type: "DEPENDENCY_MANIFEST",
        pathGlob: "package.json",
        description: "package.json present",
      },
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "src/**/*.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one source file under src/",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "**/*.{test,spec}.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one test file",
      },
      {
        id: "openapi",
        level: "required",
        type: "API_SPEC",
        pathGlob: "{openapi.yaml,openapi.yml,openapi.json,swagger.yaml,swagger.yml}",
        description: "OpenAPI or Swagger spec at repo root",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
      {
        id: "tsconfig",
        level: "recommended",
        type: "BUILD",
        pathGlob: "tsconfig.json",
        description: "TypeScript config",
      },
    ],
    relationshipRules: [
      {
        id: "tests-link",
        level: "recommended",
        relationshipType: "TESTS",
        check: "test-naming-sibling",
        description: "Tests linked to sibling sources",
      },
      {
        id: "docs-link",
        level: "recommended",
        relationshipType: "DOCUMENTS",
        check: "any-documents-edge",
        description: "Spec or docs linked to implementation",
      },
    ],
  },
  generic: {
    id: "generic",
    name: "Generic project",
    description: "README, source, and tests — language-light",
    rules: [
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "**/*.{ts,tsx,js,jsx,py,go,rs,java}",
        minCount: 1,
        description: "At least one source file",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "**/*.{test,spec}.{ts,tsx,js,jsx}",
        minCount: 1,
        description: "At least one JS/TS-style test file",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
    ],
  },
  go: {
    id: "go",
    name: "Go module",
    description: "go.mod, packages, *_test.go",
    rules: [
      {
        id: "manifest",
        level: "required",
        type: "DEPENDENCY_MANIFEST",
        pathGlob: "go.mod",
        description: "go.mod present",
      },
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "**/*.go",
        minCount: 1,
        description: "At least one Go source file",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "**/*_test.go",
        minCount: 1,
        description: "At least one *_test.go file",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
    ],
  },
  python: {
    id: "python",
    name: "Python project",
    description: "pyproject/requirements, package code, pytest-style tests",
    rules: [
      {
        id: "manifest",
        level: "required",
        type: "DEPENDENCY_MANIFEST",
        pathGlob: "{pyproject.toml,requirements.txt}",
        description: "pyproject.toml or requirements.txt",
      },
      {
        id: "readme",
        level: "required",
        type: "DOCUMENTATION",
        pathGlob: "README.md",
        description: "Top-level README",
      },
      {
        id: "source",
        level: "required",
        type: "SOURCE",
        pathGlob: "**/*.py",
        minCount: 1,
        description: "At least one Python source file",
      },
      {
        id: "tests",
        level: "required",
        type: "TEST",
        pathGlob: "{**/test_*.py,**/*_test.py,tests/**/*.py}",
        minCount: 1,
        description: "At least one pytest-style test",
      },
      {
        id: "agents",
        level: "recommended",
        type: "DOCUMENTATION",
        pathGlob: "AGENTS.md",
        description: "Agent onboarding file",
      },
    ],
  },
};

export const DEFAULT_PROFILE_ID = "typescript-lib";
